version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_NAME=chess_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - ./data/redis:/var/lib/redis/data
  rake_tasks:
    build:
      context: .
      dockerfile: Dockerfile
