PIECES = [
  Piece.new(
    position_index: 1,
    piece_type: "rook",
    color: "black",
    position: "a8",
  ),
  Piece.new(
    position_index: 2,
    piece_type: "knight",
    color: "black",
    position: "b8",
  ),
  Piece.new(
    position_index: 3,
    piece_type: "bishop",
    color: "black",
    position: "c8",
  ),
  Piece.new(
    position_index: 4,
    piece_type: "queen",
    color: "black",
    position: "d8",
  ),
  Piece.new(
    position_index: 5,
    piece_type: "king",
    color: "black",
    position: "e8",
  ),
  Piece.new(
    position_index: 6,
    piece_type: "bishop",
    color: "black",
    position: "f8",
  ),
  Piece.new(
    position_index: 7,
    piece_type: "knight",
    color: "black",
    position: "g8",
  ),
  Piece.new(
    position_index: 8,
    piece_type: "rook",
    color: "black",
    position: "h8",
  ),
  Piece.new(
    position_index: 9,
    piece_type: "pawn",
    color: "black",
    position: "a7",
  ),
  Piece.new(
    position_index: 10,
    piece_type: "pawn",
    color: "black",
    position: "b7",
  ),
  Piece.new(
    position_index: 11,
    piece_type: "pawn",
    color: "black",
    position: "c7",
  ),
  Piece.new(
    position_index: 12,
    piece_type: "pawn",
    color: "black",
    position: "d7",
  ),
  Piece.new(
    position_index: 13,
    piece_type: "pawn",
    color: "black",
    position: "e7",
  ),
  Piece.new(
    position_index: 14,
    piece_type: "pawn",
    color: "black",
    position: "f7",
  ),
  Piece.new(
    position_index: 15,
    piece_type: "pawn",
    color: "black",
    position: "g7",
  ),
  Piece.new(
    position_index: 16,
    piece_type: "pawn",
    color: "black",
    position: "h7",
  ),
  Piece.new(
    position_index: 17,
    piece_type: "pawn",
    color: "white",
    position: "a2",
  ),
  Piece.new(
    position_index: 18,
    piece_type: "pawn",
    color: "white",
    position: "b2",
  ),
  Piece.new(
    position_index: 19,
    piece_type: "pawn",
    color: "white",
    position: "c2",
  ),
  Piece.new(
    position_index: 20,
    piece_type: "pawn",
    color: "white",
    position: "d2",
  ),
  Piece.new(
    position_index: 21,
    piece_type: "pawn",
    color: "white",
    position: "e2",
  ),
  Piece.new(
    position_index: 22,
    piece_type: "pawn",
    color: "white",
    position: "f2",
  ),
  Piece.new(
    position_index: 23,
    piece_type: "pawn",
    color: "white",
    position: "g2",
  ),
  Piece.new(
    position_index: 24,
    piece_type: "pawn",
    color: "white",
    position: "h2",
  ),
  Piece.new(
    position_index: 25,
    piece_type: "rook",
    color: "white",
    position: "a1",
  ),
  Piece.new(
    position_index: 26,
    piece_type: "knight",
    color: "white",
    position: "b1",
  ),
  Piece.new(
    position_index: 27,
    piece_type: "bishop",
    color: "white",
    position: "c1",
  ),
  Piece.new(
    position_index: 28,
    piece_type: "queen",
    color: "white",
    position: "d1",
  ),
  Piece.new(
    position_index: 29,
    piece_type: "king",
    color: "white",
    position: "e1",
  ),
  Piece.new(
    position_index: 30,
    piece_type: "bishop",
    color: "white",
    position: "f1",
  ),
  Piece.new(
    position_index: 31,
    piece_type: "knight",
    color: "white",
    position: "g1",
  ),
  Piece.new(
    position_index: 32,
    piece_type: "rook",
    color: "white",
    position: "h1",
  ),
]
