default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chess_development
  username: postgres
  password: postgres
  host: 0.0.0.0

test:
  <<: *default
  database: chess_test
  username: postgres
  password: postgres
  host: 0.0.0.0

production:
  <<: *default
  database: chess_production
  username: chess
  password: <%= ENV['CHESS_DATABASE_PASSWORD'] %>
